task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 21 
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/working/D-FINE/PASCAL-VOC-2007-1/train
    ann_file: /kaggle/working/D-FINE/PASCAL-VOC-2007-1/train/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader: 
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/working/D-FINE/PASCAL-VOC-2007-1/valid 
    ann_file:  /kaggle/working/D-FINE/PASCAL-VOC-2007-1/valid/_annotations.coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
